// ─────────────────────────────────────────────
//  data.js — static lookup data for dispo+
// ─────────────────────────────────────────────

const jurisdictionList = [
  "Afghanistan","Albania","Algeria","Andorra","Angola","Antigua and Barbuda",
  "Argentina","Armenia","Australia","Austria","Azerbaijan","Bahamas","Bahrain",
  "Bangladesh","Barbados","Belarus","Belgium","Belize","Benin","Bhutan","Bolivia",
  "Bosnia and Herzegovina","Botswana","Brazil","Brunei","Bulgaria","Burkina Faso",
  "Burundi","Cabo Verde","Cambodia","Cameroon","Canada","Central African Republic",
  "Chad","Chile","China","Colombia","Comoros","Congo","Costa Rica","Croatia","Cuba",
  "Cyprus","Czech Republic","Denmark","Djibouti","Dominica","Dominican Republic",
  "Ecuador","Egypt","El Salvador","Equatorial Guinea","Eritrea","Estonia","Eswatini",
  "Ethiopia","Fiji","Finland","France","Gabon","Gambia","Georgia","Germany","Ghana",
  "Great Britain","Greece","Grenada","Guatemala","Guinea","Guinea-Bissau","Guyana",
  "Haiti","Honduras","Hungary","Iceland","India","Indonesia","Iran","Iraq","Ireland",
  "Israel","Italy","Ivory Coast","Jamaica","Japan","Jordan","Kazakhstan","Kenya",
  "Kiribati","Kuwait","Kyrgyzstan","Laos","Latvia","Lebanon","Lesotho","Liberia",
  "Libya","Liechtenstein","Lithuania","Luxembourg","Madagascar","Malawi","Malaysia",
  "Maldives","Mali","Malta","Marshall Islands","Mauritania","Mauritius","Mexico",
  "Micronesia","Moldova","Monaco","Mongolia","Montenegro","Morocco","Mozambique",
  "Myanmar","Namibia","Nauru","Nepal","Netherlands","New Zealand","Nicaragua",
  "Niger","Nigeria","North Korea","North Macedonia","Norway","Oman","Pakistan",
  "Palau","Palestine","Panama","Papua New Guinea","Paraguay","Peru","Philippines",
  "Poland","Portugal","Qatar","Romania","Russia","Rwanda","Saint Kitts and Nevis",
  "Saint Lucia","Saint Vincent and the Grenadines","Samoa","San Marino",
  "Sao Tome and Principe","Saudi Arabia","Senegal","Serbia","Seychelles",
  "Sierra Leone","Singapore","Slovakia","Slovenia","Solomon Islands","Somalia",
  "South Africa","South Korea","South Sudan","Spain","Sri Lanka","Sudan","Suriname",
  "Sweden","Switzerland","Syria","Taiwan","Tajikistan","Tanzania","Thailand",
  "Timor-Leste","Togo","Tonga","Trinidad and Tobago","Tunisia","Turkey",
  "Turkmenistan","Tuvalu","UAE","Uganda","Ukraine","United Kingdom","United States",
  "Uruguay","Uzbekistan","Vanuatu","Vatican City","Venezuela","Vietnam","Yemen",
  "Zambia","Zimbabwe"
];

const citizenshipList = [
  "Afghan","Albanian","Algerian","Andorran","Angolan","Antiguan","Argentine",
  "Armenian","Australian","Austrian","Azerbaijani","Bahamian","Bahraini",
  "Bangladeshi","Barbadian","Belarusian","Belgian","Belizean","Beninese","Bhutanese",
  "Bolivian","Bosnian","Botswanan","Brazilian","Bruneian","Bulgarian","Burkinabe",
  "Burundian","Cabo Verdean","Cambodian","Cameroonian","Canadian","Central African",
  "Chadian","Chilean","Chinese","Colombian","Comorian","Congolese","Costa Rican",
  "Croatian","Cuban","Cypriot","Czech","Danish","Djiboutian","Dominican","Ecuadorian",
  "Egyptian","Salvadoran","Equatorial Guinean","Eritrean","Estonian","Swazi",
  "Ethiopian","Fijian","Finnish","French","Gabonese","Gambian","Georgian","German",
  "Ghanaian","British (Great Britain)","Greek","Grenadian","Guatemalan","Guinean",
  "Guinea-Bissauan","Guyanese","Haitian","Honduran","Hungarian","Icelandic","Indian",
  "Indonesian","Iranian","Iraqi","Irish","Israeli","Italian","Ivorian","Jamaican",
  "Japanese","Jordanian","Kazakhstani","Kenyan","I-Kiribati","Kuwaiti","Kyrgyz",
  "Laotian","Latvian","Lebanese","Basotho","Liberian","Libyan","Liechtensteiner",
  "Lithuanian","Luxembourger","Malagasy","Malawian","Malaysian","Maldivian","Malian",
  "Maltese","Marshallese","Mauritanian","Mauritian","Mexican","Micronesian",
  "Moldovan","Monegasque","Mongolian","Montenegrin","Moroccan","Mozambican",
  "Burmese","Namibian","Nauruan","Nepalese","Dutch","New Zealander","Nicaraguan",
  "Nigerien","Nigerian","North Korean","Macedonian","Norwegian","Omani","Pakistani",
  "Palauan","Palestinian","Panamanian","Papua New Guinean","Paraguayan","Peruvian",
  "Filipino","Polish","Portuguese","Qatari","Romanian","Russian","Rwandan",
  "Kittitian","Saint Lucian","Vincentian","Samoan","Sanmarinese","Sao Tomean",
  "Saudi","Senegalese","Serbian","Seychellois","Sierra Leonean","Singaporean",
  "Slovak","Slovenian","Solomon Islander","Somali","South African","South Korean",
  "South Sudanese","Spanish","Sri Lankan","Sudanese","Surinamese","Swedish","Swiss",
  "Syrian","Taiwanese","Tajik","Tanzanian","Thai","Timorese","Togolese","Tongan",
  "Trinidadian","Tunisian","Turkish","Turkmen","Tuvaluan","Emirati","Ugandan",
  "Ukrainian","British","American","Uruguayan","Uzbek","Ni-Vanuatu","Vatican",
  "Venezuelan","Vietnamese","Yemeni","Zambian","Zimbabwean"
];

const citizenshipToCountry = {
  Afghan:"Afghanistan", Albanian:"Albania", Algerian:"Algeria",
  Andorran:"Andorra", Angolan:"Angola", Antiguan:"Antigua and Barbuda",
  Argentine:"Argentina", Armenian:"Armenia", Australian:"Australia",
  Austrian:"Austria", Azerbaijani:"Azerbaijan", Bahamian:"Bahamas",
  Bahraini:"Bahrain", Bangladeshi:"Bangladesh", Barbadian:"Barbados",
  Belarusian:"Belarus", Belgian:"Belgium", Belizean:"Belize",
  Beninese:"Benin", Bhutanese:"Bhutan", Bolivian:"Bolivia",
  Bosnian:"Bosnia and Herzegovina", Botswanan:"Botswana", Brazilian:"Brazil",
  Bruneian:"Brunei", Bulgarian:"Bulgaria", Burkinabe:"Burkina Faso",
  Burundian:"Burundi", "Cabo Verdean":"Cabo Verde", Cambodian:"Cambodia",
  Cameroonian:"Cameroon", Canadian:"Canada", "Central African":"Central African Republic",
  Chadian:"Chad", Chilean:"Chile", Chinese:"China", Colombian:"Colombia",
  Comorian:"Comoros", Congolese:"Congo", "Costa Rican":"Costa Rica",
  Croatian:"Croatia", Cuban:"Cuba", Cypriot:"Cyprus", Czech:"Czech Republic",
  Danish:"Denmark", Djiboutian:"Djibouti", Dominican:"Dominican Republic",
  Ecuadorian:"Ecuador", Egyptian:"Egypt", Salvadoran:"El Salvador",
  "Equatorial Guinean":"Equatorial Guinea", Eritrean:"Eritrea", Estonian:"Estonia",
  Swazi:"Eswatini", Ethiopian:"Ethiopia", Fijian:"Fiji", Finnish:"Finland",
  French:"France", Gabonese:"Gabon", Gambian:"Gambia", Georgian:"Georgia",
  German:"Germany", Ghanaian:"Ghana", "British (Great Britain)":"Great Britain",
  Greek:"Greece", Grenadian:"Grenada", Guatemalan:"Guatemala", Guinean:"Guinea",
  "Guinea-Bissauan":"Guinea-Bissau", Guyanese:"Guyana", Haitian:"Haiti",
  Honduran:"Honduras", Hungarian:"Hungary", Icelandic:"Iceland", Indian:"India",
  Indonesian:"Indonesia", Iranian:"Iran", Iraqi:"Iraq", Irish:"Ireland",
  Israeli:"Israel", Italian:"Italy", Ivorian:"Ivory Coast", Jamaican:"Jamaica",
  Japanese:"Japan", Jordanian:"Jordan", Kazakhstani:"Kazakhstan", Kenyan:"Kenya",
  "I-Kiribati":"Kiribati", Kuwaiti:"Kuwait", Kyrgyz:"Kyrgyzstan", Laotian:"Laos",
  Latvian:"Latvia", Lebanese:"Lebanon", Basotho:"Lesotho", Liberian:"Liberia",
  Libyan:"Libya", Liechtensteiner:"Liechtenstein", Lithuanian:"Lithuania",
  Luxembourger:"Luxembourg", Malagasy:"Madagascar", Malawian:"Malawi",
  Malaysian:"Malaysia", Maldivian:"Maldives", Malian:"Mali", Maltese:"Malta",
  Marshallese:"Marshall Islands", Mauritanian:"Mauritania", Mauritian:"Mauritius",
  Mexican:"Mexico", Micronesian:"Micronesia", Moldovan:"Moldova",
  Monegasque:"Monaco", Mongolian:"Mongolia", Montenegrin:"Montenegro",
  Moroccan:"Morocco", Mozambican:"Mozambique", Burmese:"Myanmar",
  Namibian:"Namibia", Nauruan:"Nauru", Nepalese:"Nepal", Dutch:"Netherlands",
  "New Zealander":"New Zealand", Nicaraguan:"Nicaragua", Nigerien:"Niger",
  Nigerian:"Nigeria", "North Korean":"North Korea", Macedonian:"North Macedonia",
  Norwegian:"Norway", Omani:"Oman", Pakistani:"Pakistan", Palauan:"Palau",
  Palestinian:"Palestine", Panamanian:"Panama", "Papua New Guinean":"Papua New Guinea",
  Paraguayan:"Paraguay", Peruvian:"Peru", Filipino:"Philippines", Polish:"Poland",
  Portuguese:"Portugal", Qatari:"Qatar", Romanian:"Romania", Russian:"Russia",
  Rwandan:"Rwanda", Kittitian:"Saint Kitts and Nevis", "Saint Lucian":"Saint Lucia",
  Vincentian:"Saint Vincent and the Grenadines", Samoan:"Samoa",
  Sanmarinese:"San Marino", "Sao Tomean":"Sao Tome and Principe",
  Saudi:"Saudi Arabia", Senegalese:"Senegal", Serbian:"Serbia",
  Seychellois:"Seychelles", "Sierra Leonean":"Sierra Leone",
  Singaporean:"Singapore", Slovak:"Slovakia", Slovenian:"Slovenia",
  "Solomon Islander":"Solomon Islands", Somali:"Somalia",
  "South African":"South Africa", "South Korean":"South Korea",
  "South Sudanese":"South Sudan", Spanish:"Spain", "Sri Lankan":"Sri Lanka",
  Sudanese:"Sudan", Surinamese:"Suriname", Swedish:"Sweden", Swiss:"Switzerland",
  Syrian:"Syria", Taiwanese:"Taiwan", Tajik:"Tajikistan", Tanzanian:"Tanzania",
  Thai:"Thailand", Timorese:"Timor-Leste", Togolese:"Togo", Tongan:"Tonga",
  Trinidadian:"Trinidad and Tobago", Tunisian:"Tunisia", Turkish:"Turkey",
  Turkmen:"Turkmenistan", Tuvaluan:"Tuvalu", Emirati:"UAE", Ugandan:"Uganda",
  Ukrainian:"Ukraine", British:"United Kingdom", American:"United States",
  Uruguayan:"Uruguay", Uzbek:"Uzbekistan", "Ni-Vanuatu":"Vanuatu",
  Vatican:"Vatican City", Venezuelan:"Venezuela", Vietnamese:"Vietnam",
  Yemeni:"Yemen", Zambian:"Zambia", Zimbabwean:"Zimbabwe"
};

const penaltiesByCountry = {
  Pakistan: {
    "Drug Trafficking (1kg up)":    "lifetime imprisonment",
    "Drug Trafficking (1kg below)": "7 years imprisonment",
    "Counterfeit Currency":         "lifetime imprisonment",
    "Terrorism":                    "life imprisonment",
    "Corruption":                   "10 years imprisonment",
    "Embezzlement":                 "10 years imprisonment",
    "Dacoity":                      "lifetime imprisonment",
    "Fraud":                        "7 years imprisonment",
    "Extortion":                    "3 years imprisonment",
    "Gambling":                     "3 years imprisonment",
    "Human Trafficking":            "14 years imprisonment",
    "Robbery":                      "10 years imprisonment",
    "Cybercrime":                   "10 years imprisonment",
    "Bribery":                      "1 year imprisonment",
    "Kidnapping":                   "lifetime imprisonment",
    "Theft":                        "10 years imprisonment",
    "Money Laundering":             "10 years imprisonment",
    "Arms Trafficking":             "life imprisonment",
    "Smuggling Currency":           "14 years imprisonment",
    "Illegal Money Exchange":       "5 years imprisonment",
    "Smuggling Goods":              "3 years imprisonment",
    "Child Trafficking":            "life imprisonment",
    "Organized Crime":              "10 years imprisonment",
    "Vehicle Theft":                "7 years imprisonment",
    "Sex Trafficking":              "25 years imprisonment",
    "Liquor Trafficking":           "2 years imprisonment",
    "Wheat, Flour, Sugar, & Fertilizer Smuggling": "2 years imprisonment"
  },
  Bangladesh: {
    "Robbery":              "14 years imprisonment",
    "Drug Trafficking":     "life imprisonment",
    "Counterfeit Currency": "life imprisonment",
    "Extortion":            "life imprisonment",
    "Terrorism":            "life imprisonment",
    "Smuggling":            "life imprisonment"
  },
  India: {
    "Drug Trafficking":             "20 years imprisonment",
    "Illicit Liquor":               "3 years imprisonment",
    "Counterfeit Currency":         "life imprisonment",
    "Blood Smuggling":              "life imprisonment",
    "Bribery":                      "1 year imprisonment",
    "Corruption":                   "7 years imprisonment",
    "Counterfeit Goods":            "3 years imprisonment",
    "Extortion":                    "10 years imprisonment",
    "Burglary":                     "7 years imprisonment",
    "Gambling":                     "5 years imprisonment",
    "Human / Child Trafficking":    "life imprisonment",
    "Illegal Mining":               "5 years imprisonment",
    "Narcotics - Poppy Straw":      "10 years imprisonment",
    "Fraud":                        "10 years imprisonment",
    "Robbery":                      "14 years imprisonment",
    "Gold Smuggling":               "life imprisonment",
    "Terrorism":                    "life imprisonment",
    "Theft":                        "3 years imprisonment",
    "Sex Trafficking":              "10 years imprisonment"
  }
};