// ─────────────────────────────────────────────
//  playbook-index.js — static index of playbook.html
//  accordion entries (title, section, sample disposition
//  template, and any note), used by the maxpenalty.html
//  sidebar search to show a copyable template inline
//  without leaving the page.
//
//  NOTE: this is a plain data snapshot, not generated
//  automatically. If you add, rename, or edit entries
//  in playbook.html, update this list too so the search
//  stays accurate.
// ─────────────────────────────────────────────

window.playbookIndex = [
  { title: "Place of Birth Mismatch — Place of Birth", section: "standalone", template: "POB mismatch. Hit's POB is XXXXXXXX as per CMS while per KYC, user's POB is YYYYYYYY thus the match is a false positive.", note: null },
  { title: "DOB/YOB Mismatch — Date of Birth", section: "standalone", template: "DOB mismatch. Hit's DOB is XX/XX/XXXX as per KYC, user's DOB is YY/YY/YYYY thus the match is a false positive.", note: null },
  { title: "DOB/YOB Mismatch — Year of Birth", section: "standalone", template: "YOB mismatch. Hit's YOB is XX/XX/XXXX as per KYC, user's DOB is YY/YY/YYYY thus the match is a false positive.", note: null },
  { title: "DOB/YOB Mismatch — Inferred Date of Birth", section: "standalone", template: "DOB Mismatch. Per CMS, the hit was reported as 50 years old in 2020 (inferred YOB: 1970), while the KYC user was born in 2002. Therefore, the hit is considered a false positive.", note: null },
  { title: "Gender Mismatch — Gender based on Names", section: "standalone", template: "Gender mismatch. Hit is male as per CMS while as per KYC, user's full name is Rafi binte Ali, according to the Muslim naming convention 'Binte' indicates that user is female, thus the match is a false positive.", note: null },
  { title: "Gender Mismatch — Gender based Photo", section: "standalone", template: "Gender mismatch. Hit is male as per CMS, while as per KYC, user's ID shows that user is female thus the match is a false positive.", note: null },
  { title: "ID Mismatch — ID Number", section: "standalone", template: "ID number mismatch. Hit's ID number is S1234567A as per CMS while as per KYC, user's ID number is S9876543B. As both are Singapore NRIC numbers (same format and does not expire) and differ, this is a false positive.", note: null },
  { title: "Deceased Hit — Deceased", section: "standalone", template: "Hit is Deceased. Per CMS, hit was deceased since January 2025 while customer is pursuing KYC application hence this is a false positive.", note: null },
  { title: "Father's Name Mismatch — Father's Name", section: "standalone", template: "Father's name mismatch. Per CMS, hit's father's name is Faizal Hussein. Per KYC, customer's father's name is Mohamed Khalid. Hence this is a false positive.", note: null },
  { title: "Others — Mother's Name Mismatch", section: "standalone", template: "Mother's name mismatch. Per CMS, hit's motherr's name is XXXXXX . Per KYC, customer's mother's name is YYYYYYY . Hence this is a false positive.", note: null },
  { title: "Death Sentence — Death Sentence", section: "standalone", template: "Death Sentence. Per CMS, hit was sentence to death on May 2006. Per KYC, customer had completed KYC on 1 April 2026. Unlikely for the customer to have provided documents and completed KYC while imprisoned, hence this is a false positive.", note: null },
  { title: "DOB/YOB Mismatch — Age Mismatch (not yet born)", section: "standalone", template: "Age Mismatch. Per CMS, hit was arrested in June 2000 while the user was born in January 2004. The customer was not even born yet when the crime was committed hence this is a false positive.", note: null },
  { title: "DOB/YOB Mismatch — Age Mismatch (father/child)", section: "standalone", template: "Age Mismatch. Per CMS, hit was the father of Sanjeev Kumar whose born in 1975 while per KYC, the user was born in May 1, 2002. As it is highly unlikely for someone who has not been born yet to have a child, this is a false positive.", note: null },
  { title: "DOB/YOB Mismatch — Age Mismatch (age gap)", section: "standalone", template: "Age Mismatch. Per CMS, hit who was born in 1990/1991 was 30 years old (reported June 2020) while the user who was born on May 1, 1997 was just 23 years old at that time. As the hit and user have almost 7 years age gap, this is as false positive.", note: "Remission" },
  { title: "Jail Term Mismatch — Jail Term (Date Today)", section: "standalone", template: "Jail Term Mismatch. Per CMS, hit was sentenced to 205 month(s) imprisonment for thievery starting June 1, 2016. Hit is eligible for release on November 1, 2027 applying the remission period of 33.33% of the total sentence. The subject is likely to still be in prison therefore highly unlikely to have access to TikTok through a personal device, hence concluding hit as false positive.", note: null },
  { title: "Jail Term Mismatch — Jail Term (Card Issuing Date)", section: "standalone", template: "Jail term mismatch. Per CMS, hit was sentenced to 205 month(s) imprisonment for thievery starting June 1, 2016. Hit is eligible for release on November 1, 2027 applying the remission period of 33.33% of the total sentence. As it is unlikely for the hit to have been able to renew their ID during imprisonment, this hit is a false positive.", note: null },
  { title: "Full Name Mismatch — Arabic Name", section: "standalone", template: "Full name mismatch. As per CMS, hit is Abdul Majid and was arrested for being involved in gambling operations. Per KYC, customer's full name is Amir Bin Abdul Majid. As 'bin' means 'son of', 'Amir' is the customer's given name and 'Abdul Majid' is his father's name. As this is a hit against the customer's father's name, this is a false positive.", note: null },
  { title: "Full Name Mismatch — Full Name", section: "standalone", template: "Full name mismatch. Per CMS, hit is Thanh Phong Nguyen, while the customer's full name per KYC is Thanh Phuong Nguyen. As hit and customer's names have differing name elements (Phong vs Phuong), this is a false positive", note: null },
  { title: "Full Name Mismatch — EL/AL/UL", section: "standalone", template: "Full name mismatch. Per CMS, hit is Amir El Masry, while the customer's full name per KYC is Amir Masry. EL works as prefixes for Arabic surnames. Adding these prefixes may refer to a different family line hence this is a false positive.", note: null },
  { title: "Full Name Mismatch — Middle Name Mismatch", section: "standalone", template: "Middle name mismatch. Per CMS, hit is Alexandra Mae Alvarez Reyes, while the customer's full name per KYC is Alexandra Mae Trinidad Reyes. As the hit and customer have different middle names (Trinidad vs Alvarez), this is a false positive.", note: null },
  { title: "Others — Photo (racial difference)", section: "standalone", template: "Photo mismatch. Hit is Benjamin Taylor, former president of ABC corporation and his photo was found per CMS source indicating that he is Caucasian (insert URL). Per KYC, customer is Benjamin Taylor and his photo per ID indicates that he is Asian. Due to racial differences, this is a false positive.", note: null },
  { title: "Others — Photo (age difference)", section: "standalone", template: "Photo mismatch. Hit is Benjamin Taylor, former president of ABC corporation and his photo was found per CMS source dated 2023 indicating that he is a man in his late 50s (insert URL). Per KYC, customer is Benjamin Taylor and his selfie photo submitted in 2023 indicates that he is a man in his early 20s. Due to age differences, this is a false positive.", note: null },
  { title: "Others — Juvenile Anonymity", section: "supplemental", template: "Juvenile Anonymity. The report relates to an offence committed when the subject was a minor (under 18). International child-protection standards generally restrict the disclosure of juveniles' identities in legal proceedings and media reporting. As such, the presence of identifying details makes it unlikely that the report refers to the client. Therefore, the match is assessed as a false positive.", note: "UN Standard Minimum Rules Administration Juvenile" },
  { title: "Others — MACR", section: "supplemental", template: "Age Mismatch. Per CMS, hit was convicted for corruption and cheating the public in 2020. Per KYC, the user was born on 200X therefore was only XX years old while the minimum age to criminal responsibility in Pakistan is 7 years old. This is false positive.", note: null },
  { title: "Others — Age Requirement for a Certain Position", section: "supplemental", template: "Age Mismatch. Per CMS, hit was a member of the Philippines Congress since 2015 while the user was born in 2000. According to the Philippine Law, someone has to be XX years old to be member of the congress. This is false positive.", note: "Upload evidence from a reputable source." },
  { title: "Others — Age of Marriage", section: "supplemental", template: "Age Mismatch. Per CMS, hit is the spouse of XXXXXXXXX during the last report update in May 2020. Per KYC, the user was born on 200X therefore was only XX years old while the legal age to marry in China is 22 years old for men. This is a false positive.", note: "Minimum Age of Marriage per Country" },
  { title: "Others — Age to Enter a Contract", section: "supplemental", template: "Age Mismatch. Per CMS, hit was convicted for corruption and cheating the public in 2020. Per KYC, the user was born on 200X therefore was only XX years old while the legal age to enter a contract in Indonesia is 21 years old. This is false positive.", note: null },
  { title: "Others — Age of Compulsory Education", section: "supplemental", template: "Age Mismatch. Per CMS, hit was an associate in ABC Legal Firm in 2020. Per KYC, the user was born on 200X therefore was only XX years old while the Philippines Age of Compulsary Education is between 5-18 years old. This is a false positive.", note: "School system varies by country — Turkey School System, Pakistan School System, Myanmar School System." },
  { title: "Others — Convicted Felons", section: "supplemental", template: "Per CMS, hit was sentenced to 1 year imprisonment in Pakistan in 2000 for drug-trafficking. Per KYC, the customer was issued a driver's licence in Australia in 2020. Australia denies entry to felons. This is false positive.", note: "Felon not allowed" },
  { title: "Others — Wanted/Absconder (ID Issuing Date)", section: "supplemental", template: "Per CMS, hit was sentenced in absentia in 2000 for terrorism therefore is wanted by authorities. Per KYC the user was issued a national identity card in 2022. It is highly unlikely for someone wanted by autorities to be issued a government document hence this is false positive.", note: "For non-sanction hits ONLY." },
  { title: "Others — Wanted/Absconder (Livestream or LH)", section: "supplemental", template: "Per CMS, hit was sentenced in absentia in 2000 for terrorism therefore is wanted by authorities. Per Arena, user can be seen livestreaming in 2022. It is highly unlikely for someone wanted by autorities to be livestreaming and compromise their location hence this is false positive.", note: "For non-sanction hits ONLY." },
  { title: "Jail Term Mismatch — Jail Term (Livestream Date)", section: "supplemental", template: "Jail Term Mismatch. Per CMS, hit was sentenced to 105 month(s) imprisonment for thievery starting June 2016. Hit is eligible for release in April 2022 applying the remission period of 33.33% of the total sentence. The user can be seen livestreaming in Arena in 2021 while the hit was likely to still be in prison therefore highly unlikely to have access to TikTok through a personal device, hence concluding hit as false positive.", note: "For non-sanction hits ONLY." },
  { title: "Jail Term Mismatch — Jail Term (LH Content Upload Date)", section: "supplemental", template: "Jail Term Mismatch. Per CMS, hit was sentenced to 105 month(s) imprisonment for thievery starting June 2016. Hit is eligible for release in April 2022 applying the remission period of 33.33% of the total sentence. The user can be seen in the LH uploaded content in 2021 with Video ID: ________ while the hit was likely to still be in prison therefore highly unlikely to have access to TikTok through a personal device, hence concluding hit as false positive.", note: "For non-sanction hits ONLY." },
  { title: "Jail Term Mismatch — Jail Term (LH Registration Date)", section: "supplemental", template: "Jail Term Mismatch. Per CMS, hit was sentenced to 105 month(s) imprisonment for thievery starting June 2016. Hit is eligible for release in April 2022 applying the remission period of 33.33% of the total sentence. Per LH, the user registered to TikTok in May 2020 while the hit was likely to still be in prison therefore highly unlikely to have access to TikTok through a personal device, hence concluding hit as false positive.", note: "For non-sanction hits ONLY." },
  { title: "Full Name Mismatch — Full Legal Name Mismatch", section: "supplemental", template: "Legal Name Mismatch. Per CMS, hit is Rustom Padilla aka Bibi G. Hari, while the user’s full name per KYC is Bibi G. Hari. As the hit and user have differing primary names, this is a false positive.", note: "User's Name: Bibi G. Hari · Hit's Alias: Bibi G. Hari · Hit's Legal Name: Rustom Padilla." },
  { title: "Full Name Mismatch — Legal Name Mismatch (MRCL)", section: "supplemental", template: "Legal Name Mismatch. Per CMS, hit is Bibi Gandang Hari aka. Bibi Gandang, while the user’s full name per KYC is Bibi Gandang. As the hit has a added elements in the primary name (Hari), this is a false positive.", note: "User's Name: Bibi Gandang · Hit's Alias: Bibi Gandang · Hit's Legal Name: Bibi Gandang Hari." },
  { title: "Full Name Mismatch — Legal Name Mismatch (GTC)", section: "supplemental", template: "Legal Name Mismatch. Per CMS, hit is Bebe Hari aka. Bibi Hari, while the user’s full name per KYC is Bibi Hari. As the user and hit have a differing spelling in the legal names and the subject was sentenced, it is highly likely that a court or disciplinary committee has already reviewed the their documents confirming case as false positive.", note: "User's Name: Bibi Hari · Hit's Alias: Bibi Hari · Hit's Legal Name: Bebe Hari." },
  { title: "Citizenship Mismatch — Timeline from Position Held", section: "supplemental", template: "Citizenship Mismatch. Per CMS, hit is a member of the CPPCC's Standing Commit effective 2018-2022. Per KYC, customer was Singapore citizen per NRIC issued in 2019. As China public servants need to be a Chinese Citizen per the Law of the People's Republic of China on Public Servants and China does not recognise dual citizenship, this is a citizenship mismatch hence false positive.", note: null },
  { title: "Citizenship Mismatch — Birthdate to Issuing Date", section: "supplemental", template: "Citizenship Mismatch. Per CMS, hit is a citizen of PK as of 2005 when the CMS report was last updated. Per KYC, user was born in Motoling, Indonesia therefore they are likely indonesian from birth until they were issued the national ID in 2015. As Indonesia does not recognise dual citizenship, this is a citizenship mismatch hence false positive.", note: null },
  { title: "Citizenship Mismatch — Issuing Date to Expiry Date", section: "supplemental", template: "Citizenship Mismatch. Per CMS, hit is a citizen of KP as of 2021 when the CMS report was last updated. Per KYC, user is a KR citizen per the National Identity Card valid from 2020-2030. As North Korea does not recognise dual citizenship, this is a citizenship mismatch hence false positive.", note: null },
  { title: "Citizenship Mismatch — Issuing Date to Creation Date", section: "supplemental", template: "Citizenship Mismatch. Per CMS, hit is a citizen of KP as of 2021 when the CMS report was last updated. Per KYC, user is a KR citizen per the National Identity Card issued in 2020 used for KYC application in June 2026. As North Korea does not recognise dual citizenship, this is a citizenship mismatch hence false positive.", note: null },
  { title: "Citizenship Mismatch — No Timeline (superseded)", section: "supplemental", template: "Citizenship Mismatch. Per CMS, hit is a citizen of CN. Per KYC, customer was Singapore citizen per NRIC issued in 2019. As China does not recognise dual citizenship, this is a citizenship mismatch hence false positive.", note: "Updated: 07/01/2026 — this entry has been struck through/superseded in the source table." },
  { title: "Others — Photo (facial structure)", section: "supplemental", template: "Photo Mismatch. Per one of the CMS link and the user's submitted document, they have different facial structures, eye shape, eye brows, hair line and nose shape, thereby confirming that this hit is a false positive.", note: null },
  { title: "Others — Common Name", section: "supplemental", template: "Common name match. As per CMS, the hit is MOHAMAD ALI with location in Pakistan and no other identifiers noted. As per KYC, our user is MOHAMAD ALI and country of stay is Pakistan. Noted name and location match between hit and user, however as per \"TTL Onboarding Risk-Based Disposition Factors\", MOHAMAD has an incidence of 5833215 and a ratio of 1:33. While the ALI is a common name in Pakistan and has an incidence of 10946208 and ratio of 1:16. Given the commonality of the name, it is unlikely that user and hit are the same individual. Hence, this is a false positive.", note: "Common names are limited to full name with 3 or fewer name elements. For non-sanction hits ONLY." },
  { title: "Others — Residency", section: "supplemental", template: "Residency Mismatch. Per CMS, hit is a CN resident while the user is from UAE/PK. As the hit and user have different residency, this is a false positive.", note: "Schengen Area — must always be partnered with common name if no other factors are left." },
  { title: "Others — Maximum Sentence", section: "supplemental", template: "Per CMS, the hit was arrested in 2022 for terrorism. Given the severity of the crime in (hit's jurisdiction) where the maximum sentence is death penalty, they are expected to serve a long time in prison. This is false positive.", note: "Must always be partnered with common name if no other factors are left." },
  { title: "Others — Maximum Sentence (Arrested) + Issuing Date", section: "supplemental", template: "Per CMS, the hit was arrested in 2012 for terrorism. Given the severity of the crime in (hit's jurisdiction) where the maximum sentence is 10 Years Imprisonment, they would not have been issued a government document in 2020. This is false positive.", note: "Must always be partnered with common name if no other factors are left." },
];
